---
title: "Habitat sensitivity mapping of UK EEZ"
author: "Philip Haupt"
date: "25 February 2019"
output: html_document
bibliography: "references.bib"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
The United Kingdom's (UK) benthic habitat is a critical component of the marine ecosystem which supports a rich fish and benthic invertebrate communit. 

The benthic habitat is subject to a vast array of pressures in the marine environment, of which bottom towed fishing gears is the most prevalent and widesread acitvities.

Natural England provides statuary conservation advice on operations in the marine environment in National National Reserves (NNRs) in England, including terrestrial and marine environment. In the marine environment, NNRs include special Protected Areas (SPAs), Special Areas of Conservation (SACs), Marine Conservation Zones (MCZs), collecteivly referred to as Marine Protected Areas (MPas). All MPas in the england are currently multi-use areas, within which protected features exist. Protected features include habitats The call for wider seas conservation 



Fishing regulations may change in due process when the UK leaves the EU (EU exit) on the 31 March 2019, which is likely to have substantial ramifications for fisheries and fisheries management *(Appleby and Harrison, 2017)*. The Queen’s speech indicated that a new Fisheries Bill would be drafted to set domestic fishing quotas, and preserve fishing stocks (https://www.instituteforgovernment.org.uk/explainers/queens-speech). A change to fishing regulations requires that due consideration be given to the impacts of a displacement of fishing effort on the environment and to livelihoods of fishermen *(ABPmer, 2017; Guidetti, 2007)*. A displacement of fishing effort is defined here as the new or different areas where fishing effort moves to, which may be accompanied by a change in fishing gear used, in response to a change in fishing regulations (Vaughan, 2017). Previous research (studies) have shown that a displacement of fishing effort could lead to detrimental environmental and socio-economic effects (Bastardie et al., 2017; Chollet and Mumby, 2015).
The overarching aim of this project is provide advice to fisheries managers to minimise damage to UK marine ecosystems by avoiding negative impacts on the ecosystem arising from the displacement of fishing effort from the various [inshore] fisheries. Specifically, the project aims to identify recently non-fished sensitive benthic habitat, and essential fish habitat which are currently only lightly impacted, or not impacted. 





Habitat sensitivity mapping
Fishing displacement socio-economics [@Groot2014] [@Vaughan2017]
The EU Exit 
test citations: [@Bastardie2013; @Groot2014]

### Objectives
The objective of the project is to map the spatial distribution of sensitive benthic habitat in relation to 36 OSPAR standardized pressures caused by fishing activities in English territorial waters (12 NM offshore). 
 and their corresponding pressures to inform Natural England’s Conservation Advice. The study area includes the wider seas (outside of MPAs) to provide evidence of sensitive habitats which may be affected by a displacement of fishing pressures arising from different scenarios of EU Exit. 
A secondary aim for the project is develop a consolidated spatial index of the combined suite of pressures stemming from each fishing activity to provide a summarised overview of benthic habitat sensitivity to inform NE’s conservation advice. 
A third project objective is the development of maps of the sensitivity distribution for 30 fish and shellfish species within UK waters to fishing related activities. These models are underpinned by sensitivity assessments carried out at set benchmarks, and coupled with species distribution models.
A fourth objective is to link the work to policy on Sustainable Fishing within English territorial waters to provide high level direction to Natural England. Specifically this component will help develop the principles which inform advice on sustainable fishing in English territorial waters. This part of the project will attempt to develop a clear understanding of how sensitivity maps can be used to inform sustainable fishing policy and practice. 


Fishing displacement models have been developed previously [@Bastardie2013].



## Methods: Objective 1
Natural England’s exiting conservation advice database, which houses sensitivity assessments for all biotopes in English territorial waters, will be used in conjunction with existing benthic habitat maps to derive sensitivity maps for benthic habitat.

All technical work is being carried out using the R statistical environment in effort to make the work repeatable and provide instant results following updates to sensitivity assessments or updates to the benthic habitat map.

## References
